// <auto-generated />
using System;
using CandyServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandyServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CandyServer.Models.Candy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Candies");
                });

            modelBuilder.Entity("CandyServer.Models.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CandyServer.Models.Composition", b =>
                {
                    b.Property<Guid>("Id_Candy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id_Component")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CandyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id_Candy", "Id_Component");

                    b.HasIndex("CandyId");

                    b.HasIndex("ComponentId");

                    b.ToTable("Compositions");
                });

            modelBuilder.Entity("CandyServer.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CandyServer.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id_Customer")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CandyServer.Models.OrderCompaund", b =>
                {
                    b.Property<Guid>("Id_Order")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id_Candy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CandyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id_Order", "Id_Candy");

                    b.HasIndex("CandyId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCompaunds");
                });

            modelBuilder.Entity("CandyServer.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("CandyServer.Models.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id_Provider")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("CandyServer.Models.SupplyCompaund", b =>
                {
                    b.Property<Guid>("Id_Component")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id_Supply")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("SupplyId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id_Component", "Id_Supply");

                    b.HasIndex("ComponentId");

                    b.HasIndex("SupplyId");

                    b.ToTable("SupplyCompaunds");
                });

            modelBuilder.Entity("CandyServer.Models.Composition", b =>
                {
                    b.HasOne("CandyServer.Models.Candy", "Candy")
                        .WithMany("Compositions")
                        .HasForeignKey("CandyId");

                    b.HasOne("CandyServer.Models.Component", "Component")
                        .WithMany("Compositions")
                        .HasForeignKey("ComponentId");

                    b.Navigation("Candy");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("CandyServer.Models.Order", b =>
                {
                    b.HasOne("CandyServer.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CandyServer.Models.OrderCompaund", b =>
                {
                    b.HasOne("CandyServer.Models.Candy", "Candy")
                        .WithMany("OrderCompaunds")
                        .HasForeignKey("CandyId");

                    b.HasOne("CandyServer.Models.Order", "Order")
                        .WithMany("OrderCompaunds")
                        .HasForeignKey("OrderId");

                    b.Navigation("Candy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CandyServer.Models.Supply", b =>
                {
                    b.HasOne("CandyServer.Models.Provider", "Provider")
                        .WithMany("Supplies")
                        .HasForeignKey("ProviderId");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CandyServer.Models.SupplyCompaund", b =>
                {
                    b.HasOne("CandyServer.Models.Component", "Component")
                        .WithMany("SupplyCompaunds")
                        .HasForeignKey("ComponentId");

                    b.HasOne("CandyServer.Models.Supply", "Supply")
                        .WithMany("SupplyCompaunds")
                        .HasForeignKey("SupplyId");

                    b.Navigation("Component");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("CandyServer.Models.Candy", b =>
                {
                    b.Navigation("Compositions");

                    b.Navigation("OrderCompaunds");
                });

            modelBuilder.Entity("CandyServer.Models.Component", b =>
                {
                    b.Navigation("Compositions");

                    b.Navigation("SupplyCompaunds");
                });

            modelBuilder.Entity("CandyServer.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CandyServer.Models.Order", b =>
                {
                    b.Navigation("OrderCompaunds");
                });

            modelBuilder.Entity("CandyServer.Models.Provider", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("CandyServer.Models.Supply", b =>
                {
                    b.Navigation("SupplyCompaunds");
                });
#pragma warning restore 612, 618
        }
    }
}
